<a href="https://colab.research.google.com/github/samyon7/Class-4-soft/blob/master/sam225.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import requests


url = 'https://storage.googleapis.com/kaggle-data-sets/674157/1185810/bundle/archive.zip?X-Goog-Algorithm=GOOG4-RSA-SHA256&X-Goog-Credential=gcp-kaggle-com%40kaggle-161607.iam.gserviceaccount.com%2F20210318%2Fauto%2Fstorage%2Fgoog4_request&X-Goog-Date=20210318T012832Z&X-Goog-Expires=259199&X-Goog-SignedHeaders=host&X-Goog-Signature=1607c955c806f26bfc95d479e53fb2d84dbf4327591da27d4d7281aa89cc724fce35ccbc33a9f8e0afba8f42ee78c3211c96acd0e6f1ad312956d88ac73438ea01a5c73f46bd11eaf6c2ffe75a690021ef988bc91b3853189ddfc6cd6880bf7346a83e7fccfc892ce479d96ec7516a2289f0cf7d1d417c5da66e108e60ee72f5f8aef7519dec08593ea6b48cecd5048eae1be792945f44d56ef6e164b34d9a687c15c89da6e8e40a332959a9acc5ea908b18876f162a26d8341d9a1f70dc1665229f61f6f7b054de368d9035a3d8d3e21f83096d02b458552a77cf2f635015d0df085e7f04909321c50f41a6ebdc3f13a501832798e95460203fc51e0cba398c'
r = requests.get(url, allow_redirects=True)

open('dataset.zip', 'wb').write(r.content)

469442673

In [2]:
import zipfile
zip_ref = zipfile.ZipFile('dataset.zip', 'r')
zip_ref.extractall('TMP')
zip_ref.close()

In [4]:
import tensorflow as tf
import pandas as pd
import numpy as np
import os
from tensorflow.keras.preprocessing import image
import matplotlib.pyplot as plt
from tensorflow.keras.layers import Dense,GlobalAveragePooling2D,Dropout
from tensorflow.keras.preprocessing import image
from tensorflow.keras.preprocessing.image import ImageDataGenerator
from tensorflow.keras.models import Model
from tensorflow.keras.optimizers import Adam

In [21]:
import tensorflow as tf
from tensorflow.keras.optimizers import RMSprop
from tensorflow.keras.preprocessing.image import ImageDataGenerator

train_datagen =ImageDataGenerator(
    rotation_range=50,
    width_shift_range=0.2,
    height_shift_range=0.2,
    shear_range=0.2,
    zoom_range=0.2,
    horizontal_flip=True,
    fill_mode='nearest', 
)

In [65]:
IMG_SIZE = 150

train_generator = train_datagen.flow_from_directory(
  '/content/TMP',             
  target_size=(IMG_SIZE,IMG_SIZE),  
  batch_size=32,
  class_mode='categorical',       
)
    
validation_generator = train_datagen.flow_from_directory(
  '/content/TMP',
  target_size=(IMG_SIZE,IMG_SIZE),
  batch_size=32,
  class_mode='categorical',
)

Found 1356 images belonging to 4 classes.
Found 148 images belonging to 4 classes.


In [50]:
inputs = tf.keras.layers.Input(shape=(IMG_SIZE,IMG_SIZE,3)) 
x = tf.keras.layers.Conv2D(32, (2,2), activation='relu')(inputs)
x = tf.keras.layers.BatchNormalization()(x)
x = tf.keras.layers.Conv2D(32, (2,2))(x)
x = tf.keras.layers.BatchNormalization()(x)
x = tf.keras.layers.Conv2D(32, (2,2))(x)
x = tf.keras.layers.BatchNormalization()(x)
x = tf.keras.layers.BatchNormalization()(x)
x = tf.keras.layers.BatchNormalization()(x)
x1 = tf.keras.layers.Conv2D(32, (2,2))(x)
x1 = tf.keras.layers.BatchNormalization()(x1)
x1 = tf.keras.layers.Conv2D(32, (2,2))(x1)
x1 = tf.keras.layers.BatchNormalization()(x1)
x1 = tf.keras.layers.Conv2D(32, (2,2))(x1)
x1 = tf.keras.layers.BatchNormalization()(x1)
x1 = tf.keras.layers.Conv2D(32, (2,2), activation='selu')(x1)
x1 = tf.keras.layers.BatchNormalization()(x1)
x2 = tf.keras.layers.Conv2D(32, (5,5))(x)
x = tf.keras.layers.Concatenate()([x1,x2])
x = tf.keras.layers.Conv2D(64, (3,3))(x)
x = tf.keras.layers.Conv2D(64, (3,3), activation='selu')(x)
x = tf.keras.layers.Conv2D(64, (3,3))(x)
x1 = tf.keras.layers.Conv2D(64, (2,2))(x)
x1 = tf.keras.layers.Conv2D(64, (3,3))(x1)
x1 = tf.keras.layers.Conv2D(64, (3,3))(x1)
x1 = tf.keras.layers.Conv2D(64, (3,3), activation='selu')(x1)
x2 = tf.keras.layers.Conv2D(64, (2,2))(x)
x2_1 = tf.keras.layers.Conv2D(64, (2,2))(x2)
x2_1 = tf.keras.layers.Conv2D(128, (3,3))(x2_1)
x2_2 = tf.keras.layers.Conv2D(64, (4,4))(x2)
x2 = tf.keras.layers.Concatenate()([x2_1,x2_2])
x2 = tf.keras.layers.Conv2D(64, (4,4), activation='selu')(x2)
x3 = tf.keras.layers.Conv2D(64, (2,2))(x)
x3 = tf.keras.layers.Conv2D(64, (2,2))(x3)
x3 = tf.keras.layers.Conv2D(64, (5,5))(x3)
x3 = tf.keras.layers.Conv2D(128, (2,2), activation='selu')(x3)
x = tf.keras.layers.Concatenate()([x1,x2,x3])
x = tf.keras.layers.Conv2D(64, (2,2))(x)
x = tf.keras.layers.Conv2D(64, (2,2))(x)
x = tf.keras.layers.MaxPool2D(2,2)(x)
x = tf.keras.layers.Conv2D(128, (4,4), activation='selu')(x)
x = tf.keras.layers.MaxPool2D(3,3)(x)
x = tf.keras.layers.Activation('selu')(x)
x = tf.keras.layers.Conv2D(256, (3,3), activation='selu')(x)
x = tf.keras.layers.MaxPool2D(3,3)(x)
x = tf.keras.layers.Activation('selu')(x)
x3 = tf.keras.layers.Flatten()(x)
x3 = tf.keras.layers.Dropout(0.5)(x3)
x3 = tf.keras.layers.Dense(512, activation='relu')(x3)

outputs = tf.keras.layers.Dense(4, activation='softmax')(x3)
model = tf.keras.Model(inputs=inputs, outputs=outputs)

In [ ]:
dot_img_file = 'example.png'
tf.keras.utils.plot_model(model, to_file=dot_img_file, show_shapes=True)

In [51]:
model.compile(optimizer='adam',
              loss='categorical_crossentropy',
              metrics=['accuracy'])

In [52]:
class myCallback(tf.keras.callbacks.Callback):
  def on_epoch_end(self, epoch, logs={}):
    if(logs.get('accuracy') > 0.95):
      print("\nAccuracy better than target training!")
      self.model.stop_training = True

callbacks = myCallback()

In [72]:
%%time
history = model.fit(
    train_generator,
    epochs = 10,
    validation_data = validation_generator,
    callbacks=[callbacks]
)

Epoch 1/10
43/43 [==============================] - 44s 1s/step - loss: 0.1400 - accuracy: 0.9491 - val_loss: 0.1260 - val_accuracy: 0.9628
Epoch 2/10
43/43 [==============================] - 44s 1s/step - loss: 0.1265 - accuracy: 0.9454 - val_loss: 0.4573 - val_accuracy: 0.8757
Epoch 3/10
43/43 [==============================] - 44s 1s/step - loss: 0.3271 - accuracy: 0.8953 - val_loss: 0.2312 - val_accuracy: 0.9282
Epoch 4/10
43/43 [==============================] - 44s 1s/step - loss: 0.2358 - accuracy: 0.9174 - val_loss: 0.1684 - val_accuracy: 0.9568
Epoch 5/10
43/43 [==============================] - 44s 1s/step - loss: 0.1159 - accuracy: 0.9617 - val_loss: 0.1168 - val_accuracy: 0.9694

Accuracy better than target training!
CPU times: user 4min 10s, sys: 35.7 s, total: 4min 45s
Wall time: 3min 40s


In [74]:
target_names = []
for key in train_generator.class_indices:
    target_names.append(key)

validation_generator = train_datagen.flow_from_directory(
  '/content/TMP',
  target_size=(IMG_SIZE,IMG_SIZE),
  batch_size=32,
  class_mode='categorical'      
)

Found 1504 images belonging to 4 classes.


In [75]:
results = model.evaluate(validation_generator)
print("test loss, test acc:", results)

47/47 [==============================] - 21s 454ms/step - loss: 0.1168 - accuracy: 0.9694
test loss, test acc: [0.11675730347633362, 0.9694148898124695]


In [76]:
from sklearn.metrics import classification_report, confusion_matrix

validation_generator.reset()
Y_predi = model.predict_generator(validation_generator, 1504 //32-1)
y_predi = np.argmax(Y_predi, axis=1)
print('Confusion Matrix')
print(confusion_matrix(validation_generator.classes, y_predi))
print('Classification Report')
print(classification_report(validation_generator.classes, y_predi, target_names=target_names))

/usr/local/lib/python3.7/dist-packages/tensorflow/python/keras/engine/training.py:1905: UserWarning: `Model.predict_generator` is deprecated and will be removed in a future version. Please use `Model.predict`, which supports generators.
  warnings.warn('`Model.predict_generator` is deprecated and '


Confusion Matrix
[[363   7   4   2]
 [  1 367   7   1]
 [  3  14 358   1]
 [  2   4   0 370]]
Classification Report
              precision    recall  f1-score   support

     buffalo       0.98      0.97      0.97       376
    elephant       0.94      0.98      0.96       376
       rhino       0.97      0.95      0.96       376
       zebra       0.99      0.98      0.99       376

    accuracy                           0.97      1504
   macro avg       0.97      0.97      0.97      1504
weighted avg       0.97      0.97      0.97      1504



In [78]:
model.save("Hard_model.h5")

In [80]:
converter = tf.lite.TFLiteConverter.from_keras_model(model)

tflite_model = converter.convert()
with open('model.tflite', 'wb') as f:
    f.write(tflite_model)

INFO:tensorflow:Assets written to: /tmp/tmpcw370dsh/assets


INFO:tensorflow:Assets written to: /tmp/tmpcw370dsh/assets
